### ISSUE TITLE
Getting "FastifyError [Error]: fastify-plugin: fastify-opentelemetry - expected '4.x' fastify version, '5.0.0' is installed" error when trying to upgrade to fastify v5.0.0

### ISSUE THREAD

**Issue by rahulpol10** [autotelic/fastify-opentelemetry#71]
I am trying to upgrade fastify version in my project from 4.28.1 to 5.0.0 but I am getting the following error:

` throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
 FastifyError [Error]: fastify-plugin: fastify-opentelemetry - expected '4.x' fastify version, '5.0.0' is installed
     at Object.checkVersion (node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginUtils.js:125:11)
     at Object.registerPlugin (node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginUtils.js:148:16)
     at Boot.override (node_modules/.pnpm/fastify@5.0.0/node_modules/fastify/lib/pluginOverride.js:28:57)
     at Boot._loadPlugin (node_modules/.pnpm/avvio@9.0.0/node_modules/avvio/boot.js:425:25)     
     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
   code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
   statusCode: 500`

I got this error after updating fastify version requirement in the package.json. The latest version of fastify-opentelemetry is 0.21.0 which supports fastify 4.28.1
Any idea when you will upgrade fastify-opentelemetry to support fastify 5.x

**Comment by HW13** [comment]
Thanks @rahulpol10, just opened a PR for Fastify v5 support ->  #72  👍

**Comment by rahulpol10** [comment]
Tanks for quick response @HW13
